In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('handRaised.csv')

In [3]:
data.head()

handRaised  rightWrist
0        True         9.5
1        True         9.8
2        True         9.4
3        True         9.5
4        True         9.7

In [4]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
from sklearn.linear_model import LogisticRegression

X = data['rightWrist'].values.reshape(-1, 1)
y = data['handRaised'].values

clf = LogisticRegression(random_state=0).fit(X, y)
clf.predict(X)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

The model specification (in this case coefficients/weights and intercept) are stored in attributes in the `clf` object. 

In [5]:
clf.coef_

array([[0.39539964]])

In [6]:
clf.intercept_

array([-2.1007081])

In [7]:
9.5 * clf.coef_[0] + clf.intercept_[0]

array([1.65558845])

In [8]:
3.9 * clf.coef_[0] + clf.intercept_[0]

array([-0.55864952])